version: '3.4'

services:
  moda.web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  moda.web.client:
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://moda.web.api:5000
    ports:
      - "5002:3000"