export enum QK {
  // ORGANIZATION
  TEAM_OF_TEAMS_OPTIONS = 'TEAM_OF_TEAMS_OPTIONS',
  TEAM_MEMBERSHIPS = 'TEAM_MEMBERSHIPS',
  TEAM_RISKS = 'TEAM-RISKS',
  TEAM_OF_TEAMS_RISKS = 'TEAM-OF-TEAMS-RISKS',
}
