export enum QK {
  // USER MANAGEMENT
  USERS = 'USERS',
  USER_ROLES = 'USER_ROLES',
  ROLES = 'ROLES',
  PERMISSIONS = 'PERMISSIONS',

  // ORGANIZATION
  TEAM_OF_TEAMS_OPTIONS = 'TEAM_OF_TEAMS_OPTIONS',
  TEAM_MEMBERSHIPS = 'TEAM_MEMBERSHIPS',
  TEAM_RISKS = 'TEAM-RISKS',
  TEAM_OF_TEAMS_RISKS = 'TEAM-OF-TEAMS-RISKS',
  EMPLOYEES = 'EMPLOYEES',
  EMPLOYEE_OPTIONS = 'EMPLOYEE_OPTIONS',

  // PLANNING
  PLANNING_INTERVALS = 'PLANNING_INTERVALS',
  PLANNING_INTERVAL_CALENDAR = 'PLANNING_INTERVAL_CALENDAR',
  PLANNING_INTERVAL_PREDICTABILITY = 'PLANNING_INTERVAL_PREDICTABILITY',
  PLANNING_INTERVAL_ITERATIONS = 'PLANNING_INTERVAL_ITERATIONS',
  PLANNING_INTERVAL_ITERATION_TYPE_OPTIONS = 'PLANNING_INTERVAL_ITERATION_TYPE_OPTIONS',
  PLANNING_INTERVAL_TEAMS = 'PLANNING_INTERVAL_TEAMS',
  PLANNING_INTERVAL_OBJECTIVES = 'PLANNING_INTERVAL_OBJECTIVES',
  PLANNING_INTERVAL_OBJECTIVES_HEALTH_REPORT = 'PLANNING_INTERVAL_OBJECTIVES_HEALTH_REPORT',
  PLANNING_INTERVAL_OBJECTIVE_STATUSES = 'PLANNING_INTERVAL_OBJECTIVE_STATUSES',
  PLANNING_INTERVAL_OBJECTIVE_STATUS_OPTIONS = 'PLANNING_INTERVAL_OBJECTIVE_STATUS_OPTIONS',
  PLANNING_INTERVAL_TEAM_PREDICTABILITY = 'PLANNING_INTERVAL_TEAM_PREDICTABILITY',
  PLANNING_INTERVAL_RISKS = 'PLANNING_INTERVAL_RISKS',
  RISKS = 'RISKS',
  MY_RISKS = 'MY_RISKS',
  RISK_STATUS_OPTIONS = 'RISK_STATUS_OPTIONS',
  RISK_CATEGORY_OPTIONS = 'RISK_CATEGORY_OPTIONS',
  RISK_GRADE_OPTIONS = 'RISK_GRADE_OPTIONS',

  // WORK MANAGEMENT
  WORK_PROCESSES = 'WORK_PROCESSES',
  WORK_STATUSES = 'WORK_STATUSES',

  // APP INTEGRATION
  AZDO_BOARDS_CONNECTIONS = 'AZDO_BOARDS_CONNECTIONS',
  AZDO_BOARDS_CONNECTION_CONFIGURATIONS = 'AZDO_BOARDS_CONNECTIONS_CONFIGURATIONS',
  AZDO_BOARDS_CONNECTION_CONFIGURATION_TEST = 'AZDO_BOARDS_CONNECTIONS_CONFIGURATIONS_TEST',

  // LINKS
  LINKS = 'LINKS',

  // HEALTH CHECKS
  HEALTH_CHECKS = 'HEALTH_CHECKS',
  HEALTH_REPORT = 'HEALTH_REPORT',
  HEALTH_STATUS_OPTIONS = 'HEALTH_STATUS_OPTIONS',
}
