export enum QK {
  // USER MANAGEMENT
  ROLES = 'ROLES',
  PERMISSIONS = 'PERMISSIONS',

  // ORGANIZATION
  TEAM_RISKS = 'TEAM-RISKS',
  TEAM_OF_TEAMS_RISKS = 'TEAM-OF-TEAMS-RISKS',
  EMPLOYEES = 'EMPLOYEES',
  EMPLOYEE_OPTIONS = 'EMPLOYEE_OPTIONS',

  // PLANNING
  PROGRAM_INCREMENTS = 'PROGRAM_INCREMENTS',
  PROGRAM_INCREMENT_PREDICTABILITY = 'PROGRAM_INCREMENT_PREDICTABILITY',
  PROGRAM_INCREMENT_TEAMS = 'PROGRAM_INCREMENT_TEAMS',
  PROGRAM_INCREMENT_OBJECTIVES = 'PROGRAM_INCREMENT_OBJECTIVES',
  PROGRAM_INCREMENT_OBJECTIVE_STATUSES = 'PROGRAM_INCREMENT_OBJECTIVE_STATUSES',
  PROGRAM_INCREMENT_OBJECTIVE_STATUS_OPTIONS = 'PROGRAM_INCREMENT_OBJECTIVE_STATUS_OPTIONS',
  PROGRAM_INCREMENT_TEAM_PREDICTABILITY = 'PROGRAM_INCREMENT_TEAM_PREDICTABILITY',
  PROGRAM_INCREMENT_RISKS = 'PROGRAM_INCREMENT_RISKS',
  RISKS = 'RISKS',
  MY_RISKS = 'MY_RISKS',
  RISK_STATUS_OPTIONS = 'RISK_STATUS_OPTIONS',
  RISK_CATEGORY_OPTIONS = 'RISK_CATEGORY_OPTIONS',
  RISK_GRADE_OPTIONS = 'RISK_GRADE_OPTIONS',

  // APP INTEGRATION
  AZDO_BOARDS_CONNECTIONS = 'AZDO_BOARDS_CONNECTIONS',
  AZDO_BOARDS_CONNECTION_CONFIGURATIONS = 'AZDO_BOARDS_CONNECTIONS_CONFIGURATIONS',
  AZDO_BOARDS_CONNECTION_CONFIGURATION_TEST = 'AZDO_BOARDS_CONNECTIONS_CONFIGURATIONS_TEST',

  // LINKS
  LINKS = 'LINKS',

  // HEALTH CHECKS
  HEALTH_CHECKS = 'HEALTH_CHECKS',
  HEALTH_STATUS_OPTIONS = 'HEALTH_STATUS_OPTIONS',
}
