apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: moda-api
  name: moda-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: moda-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: moda-api
    spec:
      containers:
        - env:
          - name: ASPNETCORE_ENVIRONMENT
            {{- if .Values.api.development }}
            value: Development
            {{- else }}
            value: Production
            {{- end }}
          - name: ASPNETCORE_URLS
            value: http://+:5150
          - name: DatabaseSettings__ConnectionString # TODO: These need to come from values.yaml at some point
            {{- if .Values.mssql.create }}
            value: Server=mssql.moda.svc.cluster.local;Database=moda;User Id=sa;Password={{.Values.mssql.admin_password}};TrustServerCertificate=true
            {{- else }}
            value: {{ .Values.mssql.connectionString }}
            {{- end }}
          - name: HangfireSettings__Storage__ConnectionString
            {{- if .Values.mssql.create }}
            value: Server=mssql.moda.svc.cluster.local;Database=moda;User Id=sa;Password={{.Values.mssql.admin_password}};TrustServerCertificate=true
            {{- else }}
            value: {{ .Values.mssql.connectionString }}
            {{- end }}
          - name: SecuritySettings__AzureAd__ClientSecret
            valueFrom:
              secretKeyRef:
                key: moda-api-client-secret
                name: moda-api-secrets
          - name: HangfireSettings__Credentials__Password
            valueFrom:
              secretKeyRef:
                key: moda-api-hangfire-password
                name: moda-api-secrets
          envFrom:
            - configMapRef:
                name: moda-api-config
          image: awaldow/moda-api:{{.Values.api.tag | default "latest"}}
          name: moda.api
          ports:
            # - containerPort: 7021 # https port
            # - containerPort: 5000 # http port
            - containerPort: 5150 # http port
          {{- if (.Values.moda.resources) }}
          resources:
            {{- toYaml .Values.moda.resources | nindent 12 }}
          {{- end }}
      restartPolicy: Always
status: {}
