/**
 * Build-time code generator: converts each tool's JSON Schema inputSchema into
 * a static Zod schema and writes src/generated/zod-schemas.ts.
 *
 * Run via: tsx scripts/generate-zod-schemas.ts  (invoked by `npm run build`)
 */
import { jsonSchemaToZod } from 'json-schema-to-zod';
import { writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

// Dynamic import so tsx resolves the .ts source files at build time
const { toolDefinitionMap } = await import('../src/tools/index.js');

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, '../src/generated');
const outFile = join(outDir, 'zod-schemas.ts');

const lines: string[] = [
    '// AUTO-GENERATED — do not edit by hand. Regenerated by `npm run build`.',
    "import { z } from 'zod';",
    '',
    'export const zodSchemas: Map<string, z.ZodTypeAny> = new Map([',
];

for (const [name, def] of toolDefinitionMap) {
    const schemaStr = jsonSchemaToZod(def.inputSchema);
    lines.push(`    ['${name}', ${schemaStr}],`);
}

lines.push(']);', '');

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, lines.join('\n'));
console.error(`Generated ${toolDefinitionMap.size} Zod schemas → ${outFile}`);
